
.SUFFIXES:

OPT = -s -Wall
XOPT = -L/usr/X11/lib

all: clgroup clnewick cluster den difftbl denxview

difftbl: difftbl.c
	gcc $(OPT) -o difftbl difftbl.c -lm

cluster: cluster.c
	gcc $(OPT) -o cluster cluster.c -lm

den: den.c
	gcc $(OPT) -o den den.c -lm

denxview: denxview.c
	gcc $(OPT) $(XOPT) -o denxview denxview.c -lm -lX11

clgroup: clgroup.c
	gcc $(OPT) -o clgroup clgroup.c

clnewick: clnewick.c
	gcc $(OPT) -o clnewick clnewick.c
